//Suman Raj Bista for Visual Perception course work
//Masters in Computer Vision 3
//University of Burgundy
//labels for the work to be performed

#ifndef DEFINATIONS_H
#define DEFINATIONS_H
enum CV_FUNCTION_ID{
    FLIP_HORIZONTAL = 1, FLIP_VERTICAL = 2, FLIP_BOTH = 3,
    ADD_SALT_N_PEPPER = 4,
    LOGO_TOP_RIGHT = 5, LOGO_TOP_LEFT = 6, LOGO_BUTTON_LEFT = 7, LOGO_BUTTON_RIGHT = 8,
    INVERT_COLOR = 9, INVERT_GRAY = 10,
    TO_GRAY = 11, TO_HSV = 112, TO_HLS = 113, TO_YCrCb = 114, TO_XYZ = 115, TO_CIELab = 116, TO_CIELuv = 117,
    GRAY_HIST = 118, RED_HIST = 119, GREEN_HIST = 120, BLUE_HIST = 121, ALL_HIST = 122, EQUAL_HIST = 23,
    RESIZE = 24, DILATE = 25, ERODE = 26, OPEN = 27, CLOSE = 28, GRADIENT = 29,
    TOPHAT = 30, BLACKHAT = 31,
    BLUR = 32, SHARPEN = 33, MEDIAN = 34, BILATERAL = 35, GAUSSIAN = 36,CUSTOMFILTER = 37,
    SOBEL = 38, LAPLACE = 39, CANNY = 40,
    NORMALISE = 41, THRESHOLD = 12,
    HOUGHLINE = 42, HOUGHCIRCLE = 43,
    CONTOURS = 44,BOUNDINGBOX = 45, MINCIRCLE=46,MINELLIPSE=47,CONVEXHULL=48,MOMENTS =49,RECTROT = 50,
     HARIS = 52, FASTFEATURES = 53, SIFTFEATURES = 54, SURFEATURES = 55,
    SIFTMATCH = 56,  SURFMATCH = 57 ,HOMOGRAPHY = 58,
    FUND7P = 59, FUND8P = 60, FUNDRANSAC =61, CALIBRATE = 62, UNDISTORT = 64
};

#endif // DEFINATIONS_H
