/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created: Tue 29. May 01:42:53 2012
**      by: Qt User Interface Compiler version 4.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QAction>
#include <QtGui/QApplication>
#include <QtGui/QButtonGroup>
#include <QtGui/QCheckBox>
#include <QtGui/QDoubleSpinBox>
#include <QtGui/QFrame>
#include <QtGui/QHBoxLayout>
#include <QtGui/QHeaderView>
#include <QtGui/QLabel>
#include <QtGui/QMainWindow>
#include <QtGui/QMenu>
#include <QtGui/QMenuBar>
#include <QtGui/QPushButton>
#include <QtGui/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionVertical;
    QAction *actionHorizontal;
    QAction *actionBoth;
    QAction *actionEqualise;
    QAction *actionAdd_Salt_and_Pepper_Noise;
    QAction *actionRed;
    QAction *actionGreen;
    QAction *actionBlue;
    QAction *actionGray;
    QAction *actionTop_Left;
    QAction *actionTop_Right;
    QAction *actionButton_Left;
    QAction *actionButtom_Right;
    QAction *actionColor;
    QAction *actionGray_2;
    QAction *actionRGB_to_Gray;
    QAction *actionRGB_to_HSV;
    QAction *actionRGB_to_HLS;
    QAction *actionRGB_to_YCrCb;
    QAction *actionRGB_to_XYZ;
    QAction *actionRGB_to_CIE_L_a_b;
    QAction *actionRGB_to_CIE_L_u_v8;
    QAction *actionImage;
    QAction *actionVideo;
    QAction *actionWebcam;
    QAction *actionSaveImage;
    QAction *actionSaveVideo;
    QAction *actionExit;
    QAction *actionGet_Logo;
    QAction *actionALL;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionSettings;
    QAction *actionDilate;
    QAction *actionErode;
    QAction *actionOpen;
    QAction *actionClose;
    QAction *actionBlur;
    QAction *actionSobel;
    QAction *actionLaplacian;
    QAction *actionCanny;
    QAction *actionSharpen;
    QAction *actionResize;
    QAction *actionLine;
    QAction *actionCircle;
    QAction *actionContours;
    QAction *actionHarris;
    QAction *actionCalibration;
    QAction *action7_point_method;
    QAction *action_8;
    QAction *actionRANSAC;
    QAction *actionEpipole;
    QAction *actionHomography;
    QAction *actionMedian;
    QAction *actionBilateral;
    QAction *actionGaussian;
    QAction *actionExtract;
    QAction *actionMatch;
    QAction *actionExtract_2;
    QAction *actionMatch_2;
    QAction *actionExtract_3;
    QAction *actionMatch_3;
    QAction *actionMorphology_Gradient;
    QAction *actionTop_Hat;
    QAction *actionBlack_Hat;
    QAction *actionCustom_Filter;
    QAction *actionNormalise;
    QAction *actionBounding_Box;
    QAction *actionMin_Enclosing_Circle;
    QAction *actionMin_Enclosing_Ellipse;
    QAction *actionConvex_Hull;
    QAction *actionMoments;
    QAction *actionThreshold;
    QAction *actionRotated_Rectangle;
    QAction *actionGet_second_Image_for_Matching;
    QAction *actionGet_Second_Image;
    QAction *actionGet_Images_from_WebCam;
    QAction *actionCalibrate;
    QAction *actionUndistort_Image;
    QAction *actionGet_Images_for_Calibration_from_Webcam;
    QAction *actionAbout;
    QAction *actionHtml;
    QAction *actionPdf;
    QWidget *centralWidget;
    QFrame *inputFrame;
    QFrame *outputFrame;
    QWidget *layoutWidget;
    QHBoxLayout *horizontalLayout_3;
    QCheckBox *checkBox_ip;
    QHBoxLayout *horizontalLayout_2;
    QCheckBox *checkBox_op;
    QHBoxLayout *horizontalLayout;
    QLabel *label;
    QPushButton *playButton;
    QPushButton *PauseButton;
    QPushButton *stopButton;
    QWidget *layoutWidget1;
    QHBoxLayout *horizontalLayout_4;
    QCheckBox *checkBox;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_3;
    QFrame *frame;
    QDoubleSpinBox *m11;
    QDoubleSpinBox *m12;
    QDoubleSpinBox *m13;
    QDoubleSpinBox *m21;
    QDoubleSpinBox *m22;
    QDoubleSpinBox *m23;
    QDoubleSpinBox *m31;
    QDoubleSpinBox *m32;
    QDoubleSpinBox *m33;
    QLabel *labeltext;
    QMenuBar *menuBar;
    QMenu *menuFlip;
    QMenu *menuInvert;
    QMenu *menuInvert_2;
    QMenu *menuHistogram;
    QMenu *menuCompute;
    QMenu *menuColor_Space_Conversion;
    QMenu *menuInsert_Logo;
    QMenu *menuOpen;
    QMenu *menuEdit;
    QMenu *menuMorphology;
    QMenu *menuFilters;
    QMenu *menuEdge;
    QMenu *menuExtract_Features;
    QMenu *menuHough_Transform;
    QMenu *menuCorners;
    QMenu *menuFAST;
    QMenu *menuSIFT;
    QMenu *menuSURF;
    QMenu *menuShape_Descriptors;
    QMenu *menuCamera;
    QMenu *menuFundamental_Matrix;
    QMenu *menuCalibrate;
    QMenu *menuHelp;
    QMenu *menuUser_Manual;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(989, 561);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(989, 561));
        MainWindow->setMaximumSize(QSize(989, 561));
        actionVertical = new QAction(MainWindow);
        actionVertical->setObjectName(QString::fromUtf8("actionVertical"));
        actionVertical->setCheckable(false);
        actionHorizontal = new QAction(MainWindow);
        actionHorizontal->setObjectName(QString::fromUtf8("actionHorizontal"));
        actionBoth = new QAction(MainWindow);
        actionBoth->setObjectName(QString::fromUtf8("actionBoth"));
        actionEqualise = new QAction(MainWindow);
        actionEqualise->setObjectName(QString::fromUtf8("actionEqualise"));
        actionAdd_Salt_and_Pepper_Noise = new QAction(MainWindow);
        actionAdd_Salt_and_Pepper_Noise->setObjectName(QString::fromUtf8("actionAdd_Salt_and_Pepper_Noise"));
        actionRed = new QAction(MainWindow);
        actionRed->setObjectName(QString::fromUtf8("actionRed"));
        actionGreen = new QAction(MainWindow);
        actionGreen->setObjectName(QString::fromUtf8("actionGreen"));
        actionBlue = new QAction(MainWindow);
        actionBlue->setObjectName(QString::fromUtf8("actionBlue"));
        actionGray = new QAction(MainWindow);
        actionGray->setObjectName(QString::fromUtf8("actionGray"));
        actionTop_Left = new QAction(MainWindow);
        actionTop_Left->setObjectName(QString::fromUtf8("actionTop_Left"));
        actionTop_Right = new QAction(MainWindow);
        actionTop_Right->setObjectName(QString::fromUtf8("actionTop_Right"));
        actionButton_Left = new QAction(MainWindow);
        actionButton_Left->setObjectName(QString::fromUtf8("actionButton_Left"));
        actionButtom_Right = new QAction(MainWindow);
        actionButtom_Right->setObjectName(QString::fromUtf8("actionButtom_Right"));
        actionColor = new QAction(MainWindow);
        actionColor->setObjectName(QString::fromUtf8("actionColor"));
        actionGray_2 = new QAction(MainWindow);
        actionGray_2->setObjectName(QString::fromUtf8("actionGray_2"));
        actionRGB_to_Gray = new QAction(MainWindow);
        actionRGB_to_Gray->setObjectName(QString::fromUtf8("actionRGB_to_Gray"));
        actionRGB_to_HSV = new QAction(MainWindow);
        actionRGB_to_HSV->setObjectName(QString::fromUtf8("actionRGB_to_HSV"));
        actionRGB_to_HLS = new QAction(MainWindow);
        actionRGB_to_HLS->setObjectName(QString::fromUtf8("actionRGB_to_HLS"));
        actionRGB_to_YCrCb = new QAction(MainWindow);
        actionRGB_to_YCrCb->setObjectName(QString::fromUtf8("actionRGB_to_YCrCb"));
        actionRGB_to_XYZ = new QAction(MainWindow);
        actionRGB_to_XYZ->setObjectName(QString::fromUtf8("actionRGB_to_XYZ"));
        actionRGB_to_CIE_L_a_b = new QAction(MainWindow);
        actionRGB_to_CIE_L_a_b->setObjectName(QString::fromUtf8("actionRGB_to_CIE_L_a_b"));
        actionRGB_to_CIE_L_u_v8 = new QAction(MainWindow);
        actionRGB_to_CIE_L_u_v8->setObjectName(QString::fromUtf8("actionRGB_to_CIE_L_u_v8"));
        actionImage = new QAction(MainWindow);
        actionImage->setObjectName(QString::fromUtf8("actionImage"));
        actionImage->setIconVisibleInMenu(true);
        actionVideo = new QAction(MainWindow);
        actionVideo->setObjectName(QString::fromUtf8("actionVideo"));
        actionWebcam = new QAction(MainWindow);
        actionWebcam->setObjectName(QString::fromUtf8("actionWebcam"));
        actionSaveImage = new QAction(MainWindow);
        actionSaveImage->setObjectName(QString::fromUtf8("actionSaveImage"));
        actionSaveVideo = new QAction(MainWindow);
        actionSaveVideo->setObjectName(QString::fromUtf8("actionSaveVideo"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionGet_Logo = new QAction(MainWindow);
        actionGet_Logo->setObjectName(QString::fromUtf8("actionGet_Logo"));
        actionALL = new QAction(MainWindow);
        actionALL->setObjectName(QString::fromUtf8("actionALL"));
        actionUndo = new QAction(MainWindow);
        actionUndo->setObjectName(QString::fromUtf8("actionUndo"));
        actionRedo = new QAction(MainWindow);
        actionRedo->setObjectName(QString::fromUtf8("actionRedo"));
        actionSettings = new QAction(MainWindow);
        actionSettings->setObjectName(QString::fromUtf8("actionSettings"));
        actionDilate = new QAction(MainWindow);
        actionDilate->setObjectName(QString::fromUtf8("actionDilate"));
        actionErode = new QAction(MainWindow);
        actionErode->setObjectName(QString::fromUtf8("actionErode"));
        actionOpen = new QAction(MainWindow);
        actionOpen->setObjectName(QString::fromUtf8("actionOpen"));
        actionClose = new QAction(MainWindow);
        actionClose->setObjectName(QString::fromUtf8("actionClose"));
        actionBlur = new QAction(MainWindow);
        actionBlur->setObjectName(QString::fromUtf8("actionBlur"));
        actionSobel = new QAction(MainWindow);
        actionSobel->setObjectName(QString::fromUtf8("actionSobel"));
        actionLaplacian = new QAction(MainWindow);
        actionLaplacian->setObjectName(QString::fromUtf8("actionLaplacian"));
        actionCanny = new QAction(MainWindow);
        actionCanny->setObjectName(QString::fromUtf8("actionCanny"));
        actionSharpen = new QAction(MainWindow);
        actionSharpen->setObjectName(QString::fromUtf8("actionSharpen"));
        actionResize = new QAction(MainWindow);
        actionResize->setObjectName(QString::fromUtf8("actionResize"));
        actionLine = new QAction(MainWindow);
        actionLine->setObjectName(QString::fromUtf8("actionLine"));
        actionCircle = new QAction(MainWindow);
        actionCircle->setObjectName(QString::fromUtf8("actionCircle"));
        actionContours = new QAction(MainWindow);
        actionContours->setObjectName(QString::fromUtf8("actionContours"));
        actionHarris = new QAction(MainWindow);
        actionHarris->setObjectName(QString::fromUtf8("actionHarris"));
        actionCalibration = new QAction(MainWindow);
        actionCalibration->setObjectName(QString::fromUtf8("actionCalibration"));
        action7_point_method = new QAction(MainWindow);
        action7_point_method->setObjectName(QString::fromUtf8("action7_point_method"));
        action_8 = new QAction(MainWindow);
        action_8->setObjectName(QString::fromUtf8("action_8"));
        actionRANSAC = new QAction(MainWindow);
        actionRANSAC->setObjectName(QString::fromUtf8("actionRANSAC"));
        actionEpipole = new QAction(MainWindow);
        actionEpipole->setObjectName(QString::fromUtf8("actionEpipole"));
        actionHomography = new QAction(MainWindow);
        actionHomography->setObjectName(QString::fromUtf8("actionHomography"));
        actionMedian = new QAction(MainWindow);
        actionMedian->setObjectName(QString::fromUtf8("actionMedian"));
        actionBilateral = new QAction(MainWindow);
        actionBilateral->setObjectName(QString::fromUtf8("actionBilateral"));
        actionGaussian = new QAction(MainWindow);
        actionGaussian->setObjectName(QString::fromUtf8("actionGaussian"));
        actionExtract = new QAction(MainWindow);
        actionExtract->setObjectName(QString::fromUtf8("actionExtract"));
        actionMatch = new QAction(MainWindow);
        actionMatch->setObjectName(QString::fromUtf8("actionMatch"));
        actionExtract_2 = new QAction(MainWindow);
        actionExtract_2->setObjectName(QString::fromUtf8("actionExtract_2"));
        actionMatch_2 = new QAction(MainWindow);
        actionMatch_2->setObjectName(QString::fromUtf8("actionMatch_2"));
        actionExtract_3 = new QAction(MainWindow);
        actionExtract_3->setObjectName(QString::fromUtf8("actionExtract_3"));
        actionMatch_3 = new QAction(MainWindow);
        actionMatch_3->setObjectName(QString::fromUtf8("actionMatch_3"));
        actionMorphology_Gradient = new QAction(MainWindow);
        actionMorphology_Gradient->setObjectName(QString::fromUtf8("actionMorphology_Gradient"));
        actionTop_Hat = new QAction(MainWindow);
        actionTop_Hat->setObjectName(QString::fromUtf8("actionTop_Hat"));
        actionBlack_Hat = new QAction(MainWindow);
        actionBlack_Hat->setObjectName(QString::fromUtf8("actionBlack_Hat"));
        actionCustom_Filter = new QAction(MainWindow);
        actionCustom_Filter->setObjectName(QString::fromUtf8("actionCustom_Filter"));
        actionNormalise = new QAction(MainWindow);
        actionNormalise->setObjectName(QString::fromUtf8("actionNormalise"));
        actionBounding_Box = new QAction(MainWindow);
        actionBounding_Box->setObjectName(QString::fromUtf8("actionBounding_Box"));
        actionMin_Enclosing_Circle = new QAction(MainWindow);
        actionMin_Enclosing_Circle->setObjectName(QString::fromUtf8("actionMin_Enclosing_Circle"));
        actionMin_Enclosing_Ellipse = new QAction(MainWindow);
        actionMin_Enclosing_Ellipse->setObjectName(QString::fromUtf8("actionMin_Enclosing_Ellipse"));
        actionConvex_Hull = new QAction(MainWindow);
        actionConvex_Hull->setObjectName(QString::fromUtf8("actionConvex_Hull"));
        actionMoments = new QAction(MainWindow);
        actionMoments->setObjectName(QString::fromUtf8("actionMoments"));
        actionThreshold = new QAction(MainWindow);
        actionThreshold->setObjectName(QString::fromUtf8("actionThreshold"));
        actionRotated_Rectangle = new QAction(MainWindow);
        actionRotated_Rectangle->setObjectName(QString::fromUtf8("actionRotated_Rectangle"));
        actionGet_second_Image_for_Matching = new QAction(MainWindow);
        actionGet_second_Image_for_Matching->setObjectName(QString::fromUtf8("actionGet_second_Image_for_Matching"));
        actionGet_Second_Image = new QAction(MainWindow);
        actionGet_Second_Image->setObjectName(QString::fromUtf8("actionGet_Second_Image"));
        actionGet_Images_from_WebCam = new QAction(MainWindow);
        actionGet_Images_from_WebCam->setObjectName(QString::fromUtf8("actionGet_Images_from_WebCam"));
        actionCalibrate = new QAction(MainWindow);
        actionCalibrate->setObjectName(QString::fromUtf8("actionCalibrate"));
        actionUndistort_Image = new QAction(MainWindow);
        actionUndistort_Image->setObjectName(QString::fromUtf8("actionUndistort_Image"));
        actionGet_Images_for_Calibration_from_Webcam = new QAction(MainWindow);
        actionGet_Images_for_Calibration_from_Webcam->setObjectName(QString::fromUtf8("actionGet_Images_for_Calibration_from_Webcam"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionHtml = new QAction(MainWindow);
        actionHtml->setObjectName(QString::fromUtf8("actionHtml"));
        actionPdf = new QAction(MainWindow);
        actionPdf->setObjectName(QString::fromUtf8("actionPdf"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QString::fromUtf8("centralWidget"));
        sizePolicy.setHeightForWidth(centralWidget->sizePolicy().hasHeightForWidth());
        centralWidget->setSizePolicy(sizePolicy);
        centralWidget->setMinimumSize(QSize(989, 562));
        centralWidget->setMaximumSize(QSize(989, 561));
        inputFrame = new QFrame(centralWidget);
        inputFrame->setObjectName(QString::fromUtf8("inputFrame"));
        inputFrame->setGeometry(QRect(10, 50, 480, 408));
        outputFrame = new QFrame(centralWidget);
        outputFrame->setObjectName(QString::fromUtf8("outputFrame"));
        outputFrame->setGeometry(QRect(500, 50, 480, 408));
        layoutWidget = new QWidget(centralWidget);
        layoutWidget->setObjectName(QString::fromUtf8("layoutWidget"));
        layoutWidget->setGeometry(QRect(10, 20, 971, 31));
        horizontalLayout_3 = new QHBoxLayout(layoutWidget);
        horizontalLayout_3->setSpacing(6);
        horizontalLayout_3->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_3->setObjectName(QString::fromUtf8("horizontalLayout_3"));
        horizontalLayout_3->setContentsMargins(0, 0, 0, 0);
        checkBox_ip = new QCheckBox(layoutWidget);
        checkBox_ip->setObjectName(QString::fromUtf8("checkBox_ip"));

        horizontalLayout_3->addWidget(checkBox_ip);

        horizontalLayout_2 = new QHBoxLayout();
        horizontalLayout_2->setSpacing(6);
        horizontalLayout_2->setObjectName(QString::fromUtf8("horizontalLayout_2"));
        checkBox_op = new QCheckBox(layoutWidget);
        checkBox_op->setObjectName(QString::fromUtf8("checkBox_op"));

        horizontalLayout_2->addWidget(checkBox_op);

        horizontalLayout = new QHBoxLayout();
        horizontalLayout->setSpacing(6);
        horizontalLayout->setObjectName(QString::fromUtf8("horizontalLayout"));
        label = new QLabel(layoutWidget);
        label->setObjectName(QString::fromUtf8("label"));

        horizontalLayout->addWidget(label);

        playButton = new QPushButton(layoutWidget);
        playButton->setObjectName(QString::fromUtf8("playButton"));
        QIcon icon;
        icon.addFile(QString::fromUtf8(":/Play"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QString::fromUtf8(":/Pause"), QSize(), QIcon::Normal, QIcon::On);
        playButton->setIcon(icon);

        horizontalLayout->addWidget(playButton);

        PauseButton = new QPushButton(layoutWidget);
        PauseButton->setObjectName(QString::fromUtf8("PauseButton"));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8(":/Pause"), QSize(), QIcon::Normal, QIcon::Off);
        icon1.addFile(QString::fromUtf8(":/Play"), QSize(), QIcon::Normal, QIcon::On);
        PauseButton->setIcon(icon1);

        horizontalLayout->addWidget(PauseButton);

        stopButton = new QPushButton(layoutWidget);
        stopButton->setObjectName(QString::fromUtf8("stopButton"));
        QIcon icon2;
        icon2.addFile(QString::fromUtf8(":/Stop"), QSize(), QIcon::Normal, QIcon::Off);
        stopButton->setIcon(icon2);

        horizontalLayout->addWidget(stopButton);


        horizontalLayout_2->addLayout(horizontalLayout);


        horizontalLayout_3->addLayout(horizontalLayout_2);

        layoutWidget1 = new QWidget(centralWidget);
        layoutWidget1->setObjectName(QString::fromUtf8("layoutWidget1"));
        layoutWidget1->setGeometry(QRect(590, 0, 388, 19));
        horizontalLayout_4 = new QHBoxLayout(layoutWidget1);
        horizontalLayout_4->setSpacing(6);
        horizontalLayout_4->setContentsMargins(11, 11, 11, 11);
        horizontalLayout_4->setObjectName(QString::fromUtf8("horizontalLayout_4"));
        horizontalLayout_4->setContentsMargins(0, 0, 0, 0);
        checkBox = new QCheckBox(layoutWidget1);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));

        horizontalLayout_4->addWidget(checkBox);

        checkBox_2 = new QCheckBox(layoutWidget1);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));

        horizontalLayout_4->addWidget(checkBox_2);

        checkBox_3 = new QCheckBox(layoutWidget1);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setChecked(true);

        horizontalLayout_4->addWidget(checkBox_3);

        frame = new QFrame(centralWidget);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(330, 460, 371, 71));
        frame->setAutoFillBackground(true);
        frame->setFrameShape(QFrame::StyledPanel);
        frame->setFrameShadow(QFrame::Raised);
        m11 = new QDoubleSpinBox(frame);
        m11->setObjectName(QString::fromUtf8("m11"));
        m11->setGeometry(QRect(160, 0, 62, 22));
        m11->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m11->setDecimals(4);
        m11->setMinimum(-1e+09);
        m11->setMaximum(1e+09);
        m11->setSingleStep(0.0001);
        m12 = new QDoubleSpinBox(frame);
        m12->setObjectName(QString::fromUtf8("m12"));
        m12->setGeometry(QRect(230, 0, 62, 22));
        m12->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m12->setDecimals(4);
        m12->setMinimum(-1e+09);
        m12->setMaximum(1e+09);
        m12->setSingleStep(0.0001);
        m13 = new QDoubleSpinBox(frame);
        m13->setObjectName(QString::fromUtf8("m13"));
        m13->setGeometry(QRect(300, 0, 62, 22));
        m13->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m13->setDecimals(4);
        m13->setMinimum(-1e+09);
        m13->setMaximum(1e+09);
        m13->setSingleStep(0.0001);
        m21 = new QDoubleSpinBox(frame);
        m21->setObjectName(QString::fromUtf8("m21"));
        m21->setGeometry(QRect(160, 20, 62, 22));
        m21->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m21->setDecimals(4);
        m21->setMinimum(-1e+09);
        m21->setMaximum(1e+09);
        m21->setSingleStep(0.0001);
        m22 = new QDoubleSpinBox(frame);
        m22->setObjectName(QString::fromUtf8("m22"));
        m22->setGeometry(QRect(230, 20, 62, 22));
        m22->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m22->setDecimals(4);
        m22->setMinimum(-1e+09);
        m22->setMaximum(1e+09);
        m22->setSingleStep(0.0001);
        m23 = new QDoubleSpinBox(frame);
        m23->setObjectName(QString::fromUtf8("m23"));
        m23->setGeometry(QRect(300, 20, 62, 22));
        m23->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m23->setDecimals(4);
        m23->setMinimum(-1e+09);
        m23->setMaximum(1e+09);
        m23->setSingleStep(0.0001);
        m31 = new QDoubleSpinBox(frame);
        m31->setObjectName(QString::fromUtf8("m31"));
        m31->setGeometry(QRect(160, 40, 62, 22));
        m31->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m31->setDecimals(4);
        m31->setMinimum(-1e+09);
        m31->setMaximum(1e+09);
        m31->setSingleStep(0.0001);
        m32 = new QDoubleSpinBox(frame);
        m32->setObjectName(QString::fromUtf8("m32"));
        m32->setGeometry(QRect(230, 40, 62, 22));
        m32->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m32->setDecimals(4);
        m32->setMinimum(-1e+09);
        m32->setMaximum(1e+09);
        m32->setSingleStep(0.0001);
        m33 = new QDoubleSpinBox(frame);
        m33->setObjectName(QString::fromUtf8("m33"));
        m33->setGeometry(QRect(300, 40, 62, 22));
        m33->setButtonSymbols(QAbstractSpinBox::NoButtons);
        m33->setDecimals(4);
        m33->setMinimum(-1e+09);
        m33->setMaximum(1e+09);
        m33->setSingleStep(0.0001);
        labeltext = new QLabel(frame);
        labeltext->setObjectName(QString::fromUtf8("labeltext"));
        labeltext->setGeometry(QRect(20, 20, 121, 16));
        MainWindow->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QString::fromUtf8("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 989, 21));
        menuFlip = new QMenu(menuBar);
        menuFlip->setObjectName(QString::fromUtf8("menuFlip"));
        menuInvert = new QMenu(menuBar);
        menuInvert->setObjectName(QString::fromUtf8("menuInvert"));
        menuInvert_2 = new QMenu(menuInvert);
        menuInvert_2->setObjectName(QString::fromUtf8("menuInvert_2"));
        menuHistogram = new QMenu(menuBar);
        menuHistogram->setObjectName(QString::fromUtf8("menuHistogram"));
        menuCompute = new QMenu(menuHistogram);
        menuCompute->setObjectName(QString::fromUtf8("menuCompute"));
        menuColor_Space_Conversion = new QMenu(menuBar);
        menuColor_Space_Conversion->setObjectName(QString::fromUtf8("menuColor_Space_Conversion"));
        menuInsert_Logo = new QMenu(menuBar);
        menuInsert_Logo->setObjectName(QString::fromUtf8("menuInsert_Logo"));
        menuOpen = new QMenu(menuBar);
        menuOpen->setObjectName(QString::fromUtf8("menuOpen"));
        menuEdit = new QMenu(menuBar);
        menuEdit->setObjectName(QString::fromUtf8("menuEdit"));
        menuMorphology = new QMenu(menuBar);
        menuMorphology->setObjectName(QString::fromUtf8("menuMorphology"));
        menuFilters = new QMenu(menuBar);
        menuFilters->setObjectName(QString::fromUtf8("menuFilters"));
        menuEdge = new QMenu(menuFilters);
        menuEdge->setObjectName(QString::fromUtf8("menuEdge"));
        menuExtract_Features = new QMenu(menuBar);
        menuExtract_Features->setObjectName(QString::fromUtf8("menuExtract_Features"));
        menuHough_Transform = new QMenu(menuExtract_Features);
        menuHough_Transform->setObjectName(QString::fromUtf8("menuHough_Transform"));
        menuCorners = new QMenu(menuExtract_Features);
        menuCorners->setObjectName(QString::fromUtf8("menuCorners"));
        menuFAST = new QMenu(menuExtract_Features);
        menuFAST->setObjectName(QString::fromUtf8("menuFAST"));
        menuSIFT = new QMenu(menuExtract_Features);
        menuSIFT->setObjectName(QString::fromUtf8("menuSIFT"));
        menuSURF = new QMenu(menuExtract_Features);
        menuSURF->setObjectName(QString::fromUtf8("menuSURF"));
        menuShape_Descriptors = new QMenu(menuExtract_Features);
        menuShape_Descriptors->setObjectName(QString::fromUtf8("menuShape_Descriptors"));
        menuCamera = new QMenu(menuBar);
        menuCamera->setObjectName(QString::fromUtf8("menuCamera"));
        menuFundamental_Matrix = new QMenu(menuCamera);
        menuFundamental_Matrix->setObjectName(QString::fromUtf8("menuFundamental_Matrix"));
        menuCalibrate = new QMenu(menuBar);
        menuCalibrate->setObjectName(QString::fromUtf8("menuCalibrate"));
        menuHelp = new QMenu(menuBar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        menuUser_Manual = new QMenu(menuHelp);
        menuUser_Manual->setObjectName(QString::fromUtf8("menuUser_Manual"));
        MainWindow->setMenuBar(menuBar);

        menuBar->addAction(menuOpen->menuAction());
        menuBar->addAction(menuEdit->menuAction());
        menuBar->addAction(menuFlip->menuAction());
        menuBar->addAction(menuHistogram->menuAction());
        menuBar->addAction(menuColor_Space_Conversion->menuAction());
        menuBar->addAction(menuInsert_Logo->menuAction());
        menuBar->addAction(menuMorphology->menuAction());
        menuBar->addAction(menuFilters->menuAction());
        menuBar->addAction(menuExtract_Features->menuAction());
        menuBar->addAction(menuCamera->menuAction());
        menuBar->addAction(menuCalibrate->menuAction());
        menuBar->addAction(menuInvert->menuAction());
        menuBar->addAction(menuHelp->menuAction());
        menuFlip->addAction(actionVertical);
        menuFlip->addAction(actionHorizontal);
        menuFlip->addAction(actionBoth);
        menuInvert->addAction(menuInvert_2->menuAction());
        menuInvert->addAction(actionAdd_Salt_and_Pepper_Noise);
        menuInvert->addAction(actionResize);
        menuInvert->addAction(actionNormalise);
        menuInvert->addAction(actionThreshold);
        menuInvert_2->addAction(actionColor);
        menuInvert_2->addAction(actionGray_2);
        menuHistogram->addAction(menuCompute->menuAction());
        menuHistogram->addAction(actionEqualise);
        menuCompute->addAction(actionGray);
        menuCompute->addAction(actionRed);
        menuCompute->addAction(actionGreen);
        menuCompute->addAction(actionBlue);
        menuCompute->addAction(actionALL);
        menuColor_Space_Conversion->addAction(actionRGB_to_Gray);
        menuColor_Space_Conversion->addAction(actionRGB_to_HSV);
        menuColor_Space_Conversion->addAction(actionRGB_to_HLS);
        menuColor_Space_Conversion->addAction(actionRGB_to_YCrCb);
        menuColor_Space_Conversion->addAction(actionRGB_to_XYZ);
        menuColor_Space_Conversion->addAction(actionRGB_to_CIE_L_a_b);
        menuColor_Space_Conversion->addAction(actionRGB_to_CIE_L_u_v8);
        menuInsert_Logo->addAction(actionTop_Left);
        menuInsert_Logo->addAction(actionTop_Right);
        menuInsert_Logo->addAction(actionButton_Left);
        menuInsert_Logo->addAction(actionButtom_Right);
        menuInsert_Logo->addSeparator();
        menuInsert_Logo->addAction(actionGet_Logo);
        menuOpen->addAction(actionImage);
        menuOpen->addAction(actionVideo);
        menuOpen->addAction(actionWebcam);
        menuOpen->addSeparator();
        menuOpen->addAction(actionSaveImage);
        menuOpen->addAction(actionSaveVideo);
        menuOpen->addSeparator();
        menuOpen->addAction(actionExit);
        menuEdit->addAction(actionUndo);
        menuEdit->addAction(actionRedo);
        menuEdit->addSeparator();
        menuEdit->addAction(actionSettings);
        menuMorphology->addAction(actionDilate);
        menuMorphology->addAction(actionErode);
        menuMorphology->addAction(actionOpen);
        menuMorphology->addAction(actionClose);
        menuMorphology->addAction(actionMorphology_Gradient);
        menuMorphology->addAction(actionTop_Hat);
        menuMorphology->addAction(actionBlack_Hat);
        menuFilters->addAction(actionBlur);
        menuFilters->addAction(actionSharpen);
        menuFilters->addAction(menuEdge->menuAction());
        menuFilters->addAction(actionMedian);
        menuFilters->addAction(actionBilateral);
        menuFilters->addAction(actionGaussian);
        menuFilters->addAction(actionCustom_Filter);
        menuEdge->addAction(actionSobel);
        menuEdge->addAction(actionLaplacian);
        menuEdge->addAction(actionCanny);
        menuExtract_Features->addAction(menuHough_Transform->menuAction());
        menuExtract_Features->addAction(actionContours);
        menuExtract_Features->addAction(menuShape_Descriptors->menuAction());
        menuExtract_Features->addAction(menuCorners->menuAction());
        menuExtract_Features->addAction(menuFAST->menuAction());
        menuExtract_Features->addAction(menuSURF->menuAction());
        menuExtract_Features->addAction(menuSIFT->menuAction());
        menuExtract_Features->addSeparator();
        menuExtract_Features->addAction(actionGet_second_Image_for_Matching);
        menuHough_Transform->addAction(actionLine);
        menuHough_Transform->addAction(actionCircle);
        menuCorners->addAction(actionHarris);
        menuFAST->addAction(actionExtract);
        menuFAST->addAction(actionMatch);
        menuSIFT->addAction(actionExtract_2);
        menuSIFT->addAction(actionMatch_2);
        menuSURF->addAction(actionExtract_3);
        menuSURF->addAction(actionMatch_3);
        menuShape_Descriptors->addAction(actionConvex_Hull);
        menuShape_Descriptors->addAction(actionBounding_Box);
        menuShape_Descriptors->addAction(actionRotated_Rectangle);
        menuShape_Descriptors->addAction(actionMin_Enclosing_Circle);
        menuShape_Descriptors->addAction(actionMin_Enclosing_Ellipse);
        menuShape_Descriptors->addAction(actionMoments);
        menuCamera->addAction(menuFundamental_Matrix->menuAction());
        menuCamera->addAction(actionHomography);
        menuCamera->addSeparator();
        menuCamera->addAction(actionGet_Second_Image);
        menuCamera->addAction(actionGet_Images_from_WebCam);
        menuFundamental_Matrix->addAction(action7_point_method);
        menuFundamental_Matrix->addAction(action_8);
        menuFundamental_Matrix->addAction(actionRANSAC);
        menuCalibrate->addAction(actionCalibrate);
        menuCalibrate->addAction(actionUndistort_Image);
        menuCalibrate->addSeparator();
        menuCalibrate->addAction(actionGet_Images_for_Calibration_from_Webcam);
        menuHelp->addAction(menuUser_Manual->menuAction());
        menuHelp->addAction(actionAbout);
        menuUser_Manual->addAction(actionHtml);
        menuUser_Manual->addAction(actionPdf);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "VP_COURSEWORK", 0, QApplication::UnicodeUTF8));
        actionVertical->setText(QApplication::translate("MainWindow", "Vertical", 0, QApplication::UnicodeUTF8));
        actionHorizontal->setText(QApplication::translate("MainWindow", "Horizontal", 0, QApplication::UnicodeUTF8));
        actionBoth->setText(QApplication::translate("MainWindow", "Both", 0, QApplication::UnicodeUTF8));
        actionEqualise->setText(QApplication::translate("MainWindow", "Equalise", 0, QApplication::UnicodeUTF8));
        actionAdd_Salt_and_Pepper_Noise->setText(QApplication::translate("MainWindow", "Add Salt and Pepper Noise", 0, QApplication::UnicodeUTF8));
        actionRed->setText(QApplication::translate("MainWindow", "Red", 0, QApplication::UnicodeUTF8));
        actionGreen->setText(QApplication::translate("MainWindow", "Green", 0, QApplication::UnicodeUTF8));
        actionBlue->setText(QApplication::translate("MainWindow", "Blue", 0, QApplication::UnicodeUTF8));
        actionGray->setText(QApplication::translate("MainWindow", "Gray", 0, QApplication::UnicodeUTF8));
        actionTop_Left->setText(QApplication::translate("MainWindow", "Top Left", 0, QApplication::UnicodeUTF8));
        actionTop_Right->setText(QApplication::translate("MainWindow", "Top Right", 0, QApplication::UnicodeUTF8));
        actionButton_Left->setText(QApplication::translate("MainWindow", "Buttom Left", 0, QApplication::UnicodeUTF8));
        actionButtom_Right->setText(QApplication::translate("MainWindow", "Buttom Right", 0, QApplication::UnicodeUTF8));
        actionColor->setText(QApplication::translate("MainWindow", "Color", 0, QApplication::UnicodeUTF8));
        actionGray_2->setText(QApplication::translate("MainWindow", "Gray", 0, QApplication::UnicodeUTF8));
        actionRGB_to_Gray->setText(QApplication::translate("MainWindow", "RGB to Gray", 0, QApplication::UnicodeUTF8));
        actionRGB_to_HSV->setText(QApplication::translate("MainWindow", "RGB to HSV", 0, QApplication::UnicodeUTF8));
        actionRGB_to_HLS->setText(QApplication::translate("MainWindow", "RGB to HLS", 0, QApplication::UnicodeUTF8));
        actionRGB_to_YCrCb->setText(QApplication::translate("MainWindow", "RGB to YCrCb", 0, QApplication::UnicodeUTF8));
        actionRGB_to_XYZ->setText(QApplication::translate("MainWindow", "RGB to CIE XYZ", 0, QApplication::UnicodeUTF8));
        actionRGB_to_CIE_L_a_b->setText(QApplication::translate("MainWindow", "RGB to CIE L*a*b*", 0, QApplication::UnicodeUTF8));
        actionRGB_to_CIE_L_u_v8->setText(QApplication::translate("MainWindow", "RGB to CIE L*u*v8", 0, QApplication::UnicodeUTF8));
        actionImage->setText(QApplication::translate("MainWindow", "Open Image", 0, QApplication::UnicodeUTF8));
        actionVideo->setText(QApplication::translate("MainWindow", "Open Video", 0, QApplication::UnicodeUTF8));
        actionWebcam->setText(QApplication::translate("MainWindow", "Connect to Webcam", 0, QApplication::UnicodeUTF8));
        actionSaveImage->setText(QApplication::translate("MainWindow", "Save Image", 0, QApplication::UnicodeUTF8));
        actionSaveVideo->setText(QApplication::translate("MainWindow", "Save Video", 0, QApplication::UnicodeUTF8));
        actionExit->setText(QApplication::translate("MainWindow", "Exit", 0, QApplication::UnicodeUTF8));
        actionGet_Logo->setText(QApplication::translate("MainWindow", "Get Logo", 0, QApplication::UnicodeUTF8));
        actionALL->setText(QApplication::translate("MainWindow", "All", 0, QApplication::UnicodeUTF8));
        actionUndo->setText(QApplication::translate("MainWindow", "Undo", 0, QApplication::UnicodeUTF8));
        actionRedo->setText(QApplication::translate("MainWindow", "Redo", 0, QApplication::UnicodeUTF8));
        actionSettings->setText(QApplication::translate("MainWindow", "Settings", 0, QApplication::UnicodeUTF8));
        actionDilate->setText(QApplication::translate("MainWindow", "Dilate", 0, QApplication::UnicodeUTF8));
        actionErode->setText(QApplication::translate("MainWindow", "Erode", 0, QApplication::UnicodeUTF8));
        actionOpen->setText(QApplication::translate("MainWindow", "Open", 0, QApplication::UnicodeUTF8));
        actionClose->setText(QApplication::translate("MainWindow", "Close", 0, QApplication::UnicodeUTF8));
        actionBlur->setText(QApplication::translate("MainWindow", "Blur", 0, QApplication::UnicodeUTF8));
        actionSobel->setText(QApplication::translate("MainWindow", "Sobel", 0, QApplication::UnicodeUTF8));
        actionLaplacian->setText(QApplication::translate("MainWindow", "Laplacian", 0, QApplication::UnicodeUTF8));
        actionCanny->setText(QApplication::translate("MainWindow", "Canny", 0, QApplication::UnicodeUTF8));
        actionSharpen->setText(QApplication::translate("MainWindow", "Sharpen", 0, QApplication::UnicodeUTF8));
        actionResize->setText(QApplication::translate("MainWindow", "Resize ", 0, QApplication::UnicodeUTF8));
        actionLine->setText(QApplication::translate("MainWindow", "Line", 0, QApplication::UnicodeUTF8));
        actionCircle->setText(QApplication::translate("MainWindow", "Circle", 0, QApplication::UnicodeUTF8));
        actionContours->setText(QApplication::translate("MainWindow", "Contours", 0, QApplication::UnicodeUTF8));
        actionHarris->setText(QApplication::translate("MainWindow", "Harris", 0, QApplication::UnicodeUTF8));
        actionCalibration->setText(QApplication::translate("MainWindow", "Calibration", 0, QApplication::UnicodeUTF8));
        action7_point_method->setText(QApplication::translate("MainWindow", "7 Point method", 0, QApplication::UnicodeUTF8));
        action_8->setText(QApplication::translate("MainWindow", "8 Point method", 0, QApplication::UnicodeUTF8));
        actionRANSAC->setText(QApplication::translate("MainWindow", "RANSAC", 0, QApplication::UnicodeUTF8));
        actionEpipole->setText(QApplication::translate("MainWindow", "Epipole", 0, QApplication::UnicodeUTF8));
        actionHomography->setText(QApplication::translate("MainWindow", "Homography", 0, QApplication::UnicodeUTF8));
        actionMedian->setText(QApplication::translate("MainWindow", "Median", 0, QApplication::UnicodeUTF8));
        actionBilateral->setText(QApplication::translate("MainWindow", "Bilateral", 0, QApplication::UnicodeUTF8));
        actionGaussian->setText(QApplication::translate("MainWindow", "Gaussian", 0, QApplication::UnicodeUTF8));
        actionExtract->setText(QApplication::translate("MainWindow", "Extract", 0, QApplication::UnicodeUTF8));
        actionMatch->setText(QApplication::translate("MainWindow", "Match", 0, QApplication::UnicodeUTF8));
        actionExtract_2->setText(QApplication::translate("MainWindow", "Extract", 0, QApplication::UnicodeUTF8));
        actionMatch_2->setText(QApplication::translate("MainWindow", "Match", 0, QApplication::UnicodeUTF8));
        actionExtract_3->setText(QApplication::translate("MainWindow", "Extract", 0, QApplication::UnicodeUTF8));
        actionMatch_3->setText(QApplication::translate("MainWindow", "Match", 0, QApplication::UnicodeUTF8));
        actionMorphology_Gradient->setText(QApplication::translate("MainWindow", "Morphology Gradient", 0, QApplication::UnicodeUTF8));
        actionTop_Hat->setText(QApplication::translate("MainWindow", "Top Hat", 0, QApplication::UnicodeUTF8));
        actionBlack_Hat->setText(QApplication::translate("MainWindow", "Black Hat", 0, QApplication::UnicodeUTF8));
        actionCustom_Filter->setText(QApplication::translate("MainWindow", "Custom Filter", 0, QApplication::UnicodeUTF8));
        actionNormalise->setText(QApplication::translate("MainWindow", "Normalise", 0, QApplication::UnicodeUTF8));
        actionBounding_Box->setText(QApplication::translate("MainWindow", "Bounding Box", 0, QApplication::UnicodeUTF8));
        actionMin_Enclosing_Circle->setText(QApplication::translate("MainWindow", "Min Enclosing Circle", 0, QApplication::UnicodeUTF8));
        actionMin_Enclosing_Ellipse->setText(QApplication::translate("MainWindow", "Min Enclosing Ellipse", 0, QApplication::UnicodeUTF8));
        actionConvex_Hull->setText(QApplication::translate("MainWindow", "Convex Hull", 0, QApplication::UnicodeUTF8));
        actionMoments->setText(QApplication::translate("MainWindow", "Moments", 0, QApplication::UnicodeUTF8));
        actionThreshold->setText(QApplication::translate("MainWindow", "Threshold", 0, QApplication::UnicodeUTF8));
        actionRotated_Rectangle->setText(QApplication::translate("MainWindow", "Rotated Rectangle", 0, QApplication::UnicodeUTF8));
        actionGet_second_Image_for_Matching->setText(QApplication::translate("MainWindow", "Get Second Image for Matching", 0, QApplication::UnicodeUTF8));
        actionGet_Second_Image->setText(QApplication::translate("MainWindow", "Get Right Image ", 0, QApplication::UnicodeUTF8));
        actionGet_Images_from_WebCam->setText(QApplication::translate("MainWindow", "Get Left and Right Images from WebCam", 0, QApplication::UnicodeUTF8));
        actionCalibrate->setText(QApplication::translate("MainWindow", "Calibrate Camera", 0, QApplication::UnicodeUTF8));
        actionUndistort_Image->setText(QApplication::translate("MainWindow", "Undistort Image", 0, QApplication::UnicodeUTF8));
        actionGet_Images_for_Calibration_from_Webcam->setText(QApplication::translate("MainWindow", "Get Images for Calibration from Webcam", 0, QApplication::UnicodeUTF8));
        actionAbout->setText(QApplication::translate("MainWindow", "About", 0, QApplication::UnicodeUTF8));
        actionHtml->setText(QApplication::translate("MainWindow", "html", 0, QApplication::UnicodeUTF8));
        actionPdf->setText(QApplication::translate("MainWindow", "pdf", 0, QApplication::UnicodeUTF8));
        checkBox_ip->setText(QApplication::translate("MainWindow", "Popout", 0, QApplication::UnicodeUTF8));
        checkBox_op->setText(QApplication::translate("MainWindow", "Popout", 0, QApplication::UnicodeUTF8));
        label->setText(QApplication::translate("MainWindow", "Take Left Image", 0, QApplication::UnicodeUTF8));
        playButton->setText(QApplication::translate("MainWindow", "Play", 0, QApplication::UnicodeUTF8));
        PauseButton->setText(QApplication::translate("MainWindow", "Pause", 0, QApplication::UnicodeUTF8));
        stopButton->setText(QApplication::translate("MainWindow", "Stop", 0, QApplication::UnicodeUTF8));
        checkBox->setText(QApplication::translate("MainWindow", "Process Contiously", 0, QApplication::UnicodeUTF8));
        checkBox_2->setText(QApplication::translate("MainWindow", "Supress Intermediate Windows", 0, QApplication::UnicodeUTF8));
        checkBox_3->setText(QApplication::translate("MainWindow", "Show Options", 0, QApplication::UnicodeUTF8));
        labeltext->setText(QApplication::translate("MainWindow", "Fundamental Matrix   = ", 0, QApplication::UnicodeUTF8));
        menuFlip->setTitle(QApplication::translate("MainWindow", "Flip", 0, QApplication::UnicodeUTF8));
        menuInvert->setTitle(QApplication::translate("MainWindow", "Others", 0, QApplication::UnicodeUTF8));
        menuInvert_2->setTitle(QApplication::translate("MainWindow", "Invert", 0, QApplication::UnicodeUTF8));
        menuHistogram->setTitle(QApplication::translate("MainWindow", "Histogram", 0, QApplication::UnicodeUTF8));
        menuCompute->setTitle(QApplication::translate("MainWindow", "Compute", 0, QApplication::UnicodeUTF8));
        menuColor_Space_Conversion->setTitle(QApplication::translate("MainWindow", "Color Space Conversion", 0, QApplication::UnicodeUTF8));
        menuInsert_Logo->setTitle(QApplication::translate("MainWindow", "Insert Logo", 0, QApplication::UnicodeUTF8));
        menuOpen->setTitle(QApplication::translate("MainWindow", "Main", 0, QApplication::UnicodeUTF8));
        menuEdit->setTitle(QApplication::translate("MainWindow", "Edit", 0, QApplication::UnicodeUTF8));
        menuMorphology->setTitle(QApplication::translate("MainWindow", "Morphology", 0, QApplication::UnicodeUTF8));
        menuFilters->setTitle(QApplication::translate("MainWindow", "Filters", 0, QApplication::UnicodeUTF8));
        menuEdge->setTitle(QApplication::translate("MainWindow", "Edge", 0, QApplication::UnicodeUTF8));
        menuExtract_Features->setTitle(QApplication::translate("MainWindow", "Features", 0, QApplication::UnicodeUTF8));
        menuHough_Transform->setTitle(QApplication::translate("MainWindow", "Hough Transform", 0, QApplication::UnicodeUTF8));
        menuCorners->setTitle(QApplication::translate("MainWindow", "Corners", 0, QApplication::UnicodeUTF8));
        menuFAST->setTitle(QApplication::translate("MainWindow", "FAST", 0, QApplication::UnicodeUTF8));
        menuSIFT->setTitle(QApplication::translate("MainWindow", "SIFT", 0, QApplication::UnicodeUTF8));
        menuSURF->setTitle(QApplication::translate("MainWindow", "SURF", 0, QApplication::UnicodeUTF8));
        menuShape_Descriptors->setTitle(QApplication::translate("MainWindow", "Shape Descriptors", 0, QApplication::UnicodeUTF8));
        menuCamera->setTitle(QApplication::translate("MainWindow", "Compute", 0, QApplication::UnicodeUTF8));
        menuFundamental_Matrix->setTitle(QApplication::translate("MainWindow", "Fundamental Matrix", 0, QApplication::UnicodeUTF8));
        menuCalibrate->setTitle(QApplication::translate("MainWindow", "Calibration", 0, QApplication::UnicodeUTF8));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", 0, QApplication::UnicodeUTF8));
        menuUser_Manual->setTitle(QApplication::translate("MainWindow", "User Manual", 0, QApplication::UnicodeUTF8));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
